### PR TITLE
engine: do not use keywords as keys

### PR DESCRIPTION
**Pull request by kaplun**
Do not use keywords as dictionary keys, rather as elements in a list.
(Closes inspirehep/inspire-next#2456)

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by michamos** [comment]
won't this fail for the same reason it failed with the experiment guesser (inspirehep/inspire-next#2054)?

**Comment by kaplun** [comment]
Well, I now have to adapt `inspire-next` to it.

**Comment by michamos** [comment]
I mean using lists as tuples with different types inside that make ES choke.

**Comment by kaplun** [comment]
Ha! Now I understand. I am actually further fixing indeed classifier to properly output list objects rather than list of tuples.

**Pull request merged**
